id: 1
nome: '&6☘ &e&lP&r&elantio &e&lB&r&eásico &6☘'
posicao_holograma:
  x: 14
  y: 0
  z: 25
requisitos:
  nivel_ilha: 1
  itens: {}
  ouro: 0
niveis:
  nivel_1:
    nivel: 1
    schematic: nivel_1
    evolucao:
      xp: 100
      ouro: 25
      nivel: 2
  nivel_2:
    nivel: 2
    schematic: nivel_2
    evolucao: false