id: 1
posicao:
  x: 0
  y: 0
  z: 0
requisitos:
  nivel_ilha: 1
  itens: {}
  ouro: 0
niveis:
  nivel_1:
    nivel: 1
    schematic: nivel_1
    evolucao:
      xp: 100
      ouro: 25
      nivel: 2
  nivel_2:
    nivel: 2
    schematic: nivel_2
    evolucao: false