name: GrandeFazendas
main: com.grandemc.fazendas.GrandeFazendas
version: 1.0
softdepend: [Multiverse-Core]
depend: [PostLib, Vault, GrandeCash, FAWE]
commands:
  fazenda:
    description: Player main command
  gfazenda:
    description: Staff main command