name: GrandeFazendas
main: com.grandemc.fazendas.GrandeFazendas
version: 1.0
softdepend: [Multiverse-Core]
depend: [PostLib, Vault, GrandeCash, FastAsyncWorldEdit, Citizens, PlaceholderAPI]
commands:
  fazendas:
    aliases: [fazenda]
    description: Player main command
  gfazendas:
    aliases: [gfazenda]
    description: Staff main command
  xfazendas:
    aliases: [xfazenda]
    description: Staff extras command