name: GrandeFazendas
main: com.grandemc.fazendas.GrandeFazendas
version: 1.0
softdepend: [Multiverse-Core]
depend: [PostLib, Vault, GrandeCash, Multiverse-Core, FastAsyncWorldEdit, Citizens]
commands:
  fazendas:
    aliases: [fazenda]
    description: Player main command
  gfazendas:
    aliases: [gfazenda]
    description: Staff main command