id: 2
nome: '&3☘ &b&lP&r&blantio &b&lA&r&bvançado &3☘'
posicao_holograma:
  x: 0
  y: 0
  z: 38
requisitos:
  nivel_ilha: 1
  itens:
    trigo: 1k
  ouro: 1k
niveis:
  nivel_1:
    nivel: 1
    schematic: nivel_1
    evolucao:
      xp: 300
      ouro: 2k
      nivel: 2
  nivel_2:
    nivel: 2
    schematic: nivel_2
    evolucao: false